name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "ee9447f1c6c84ef5a5f3f01ccca28216"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.lius.me", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "2e337f14bbb940e1a09947374773fb19" },
  { binding = "PBIMGS", id ="85f8b248f4754241be7e3161446b23e4" }
]

[site]
bucket = "./static/dist"
